### ISSUE TITLE
Cannot show the Swagger view

### ISSUE THREAD

**Issue by nicola883** [RepreZen/KaiZen-OpenAPI-Editor#173]
I have installed the SwagEdit on Eclipse Luna.
I am able to create a new file "New Swagger Spec" and I get the sample file, so I think all is working.
But I cannot find the way to open the Swagger view, the view that you show in your video where to see the documention, in the right side.
Also I don't see the mock services button on top of the editor canvas.
Is there something I have to enable or some more plugin to add?
Many thanks for your help.

**Comment by tedepstein** [comment]
@nicola883, the video is for RepreZen API Studio, our solution for API design, documentation and delivery. 

SwagEdit is our open source Swagger–OpenAPI editor, used in API Studio.  The other features -- mock service, live Swagger-UI, documentation and diagram views, code generation and [RAPID-ML](http://rapid-api.org) -- are part of RepreZen API Studio, but not included in SwagEdit.

**Comment by tedepstein** [comment]
I realize this may have been confusing.  We repurposed this onboarding video here because we haven't yet made a video specifically for SwagEdit.  

I just updated the heading and added a note under the video to explain which features shown in the video are included in SwagEdit, which ones are contributed by open source plugins (EditBox & Eclipse Color Theme), and which features are online in API Studio.  I hope that helps.
