### ISSUE TITLE
Strange error markers when machine is offline

### ISSUE THREAD

**Issue by andylowry** [RepreZen/KaiZen-OpenAPI-Editor#180]
Here's what I see when I open API Studio showing a swagedit editor with a perfectly valid swagger spec in it:
![image](https://cloud.githubusercontent.com/assets/108675/17609810/4a9efa8c-6006-11e6-877f-059f8917cc0c.png)

Here's the Problem view:
![image](https://cloud.githubusercontent.com/assets/108675/17609814/580ffb44-6006-11e6-9420-794ba84caea8.png)

If I go online and then make an insiginificant change to the swagger spec (e.g. adding a space at the end of a description), the marker vanishes. Or if I simply close API studio, go online, and then restart, the marker clears itself shortly after startup.

**Comment by ghillairet** [comment]
This happened because we didn't correctly rewrite the error generated by the json schema validator, see my commit to fix this.
Anyway the real issue is that the swagger schema references the core json schema from http://json-schema.org/draft-04/schema, and during the validation phase, the validator will want to read that schema and will fail since it cannot access it, causing a validation error.

**Comment by ghillairet** [comment]
@tfesenko With the recent changes made on branch master (see #209),  looks like this exception is not thrown anymore when offline.

**Comment by tfesenko** [comment]
Fixed
