### ISSUE TITLE
SwagEdit Model

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenAPI-Editor#198]
This issue is to discuss all changes made to support a better representation of the content of a swagger document. Work on this is currently done in the branch task/model. 

The goals of this work is to unify the access to swagger document content, such as position and types of elements, in the different services provided by SwagEdit such as content assist, outlines, etc.. This should simplify a lot of code that now uses either the Jackson Node API or snakeyaml API to achieve this.

> Background, this work was started with quick outline, see https://github.com/RepreZen/SwagEdit/pull/176

List of tasks to be done
- [x] Implement Model parser with Jackson streaming API
- [x] Remove SchemaDefinition class, replaced by TypeDefinition and SwaggerSchema
- [x] Type definitions should be derived from swagger JSON schema
- [x] Content assist proposals should be obtained through Node type
- [x] Content assist processor should use the new Model API
- [x] JSON pointers should be used instead of previous path format to navigate inside a document
- [x] Outline label provider should use the Model API
- [x] Fix method SwaggerDocument.getRegion(node) that often returns incorrect location
- [x] Make sure tests work with maven/tycho
- [x] All tests are not yet correct, some of them are still failling
- [x] Looks like validation takes more time than before, this should be fixed

**Comment by ghillairet** [comment]
Current status on this.

The hyperlinks detectors and the content assist processor have been updated to start using the new model API.

Work on the resolution of types from the swagger schema has been started. It was previously done by using the SchemaDefinition class, which has been removed. Resolution was happening each time a call to a content assist was performed. Now all types are resolved when the editor starts and are stored and accessed by the class SwaggerSchema.

Moving all paths to JSON pointers has also been started and is yet to be completed.

**Comment by tfesenko** [comment]
Notes for @tfesenko for next week's review:

## Verify

That aliases still work with the new code

## Suggestions:
- Merge conflicts - task branch cannot be merged into master
- `com.reprezen.swagedit.json.TypeDefinition.resolve(JsonNode, JsonNode)` -> `resolveRef()`
- `com.reprezen.swagedit.json.JsonUtil.asPointer(String)` and `getPointer()` look similar. Can `getPointer()` call `asPointer()`? Why does `asPointer()` sanitize the string and `getPointer` does not?
- `path.replaceAll("~1", "/")` is used in several places, e.g. `com.reprezen.swagedit.json.ObjectTypeDefinition.findMatchingPattern(String)` and `com.reprezen.swagedit.json.TypeDefinition.getProperty(JsonPointer)`. It can be extracted to be reused instead of copying code.
- Typo - `com.reprezen.swagedit.editor.outline.OutlineStyledLabelProvider.getSyledString(AbstractNode)` - s**t**yled

## Questions:
- Relation between `TypeDefinition` and `AbstractNode`?
  - `AbstractNode` reflects JSON
  - `TypeDefinition`reflects JSON Schema, e.g. `ComplexTypeDefinition` represents complex JSON Schema types, e.g.`oneOf`, `allOf`, etc 
- Why `TypeDefinition` has four elements in hierarchy and `AbstractNode` just three?

## Changes Overview:

![swagedit_model](https://cloud.githubusercontent.com/assets/644582/18528803/7439c9e2-7a98-11e6-90bb-e5f4d263c5c0.png)

**Comment by ghillairet** [comment]
The content assist in the model branch starts to offer a better experience for typeahead (issue #58). See screencast on content assist over parameters.

![params](https://cloud.githubusercontent.com/assets/148045/18638769/a1ef0652-7e91-11e6-9b2f-f640501845bb.gif)

Another feature that it provides is better proposals for array enums, e.g. it directly propose to insert array values.

![enum_arrays](https://cloud.githubusercontent.com/assets/148045/18638803/bdde5e4e-7e91-11e6-9ed1-949063e0c5fd.gif)

**Comment by tedepstein** [comment]
Looks good, @ghillairet !

**Comment by tfesenko** [comment]
Re: the last item in the implementation outline - " Make sure tests work with maven/tycho". 
As per our today's discussion with @ghillairet .
For some reason Xtend classes fail to compile in command line Tycho if using Mockito directly. Compilation in Eclipse is OK. As a workaround we created a Java (not Xtend) class [Mocks](https://github.com/RepreZen/SwagEdit/blob/master/com.reprezen.swagedit.tests/src/com/reprezen/swagedit/mocks/Mocks.java) which creates Mocks. Then, Xtend classes can use these mocks, e.g. in [JsonReferenceProposalProviderTest](https://github.com/RepreZen/SwagEdit/blob/master/com.reprezen.swagedit.tests/src/com/reprezen/swagedit/assist/JsonReferenceProposalProviderTest.xtend)

**Comment by ghillairet** [comment]
Tests have been updated to run with maven/tycho.

**Comment by ghillairet** [comment]
About the currently failing tests, most of them are failing because of the helper methods I use to write tests for content assist. The error comes from the helper method not SwagEdit code (error should be from that method https://github.com/RepreZen/SwagEdit/blob/task/model/com.reprezen.swagedit.tests/src/com/reprezen/swagedit/tests/utils/Cursors.xtend#L48)

**Comment by tedepstein** [comment]
@ghillairet , can you please estimate how much more time you need to complete this?

**Comment by tfesenko** [comment]
I reviewed the current state, it looks goo!
I have several comments, suggestions, and recommendations, you can see them below:

## Structure

![swageditdiagrams](https://cloud.githubusercontent.com/assets/644582/18801408/877609d4-81b0-11e6-87c9-15a8601874b5.png)
1. Package naming
   As we discussed in the comment above, the "model" package reflects JSON, and the "json" package reflects the JSON Schema. It's very confusing. 
   We can also think of the current `Model` and `AbstractNodes` as of something that provides information about the syntax; and `SwaggerSchema` and `TypeDefinition` - semantics.
2. Class naming
   The new classes represent elements on the meta-level, it information description, not information itself. That's why it may be difficult to find right names. But we should try. 
   As for me, life became much easier when I started thinking of `TypeDefinition` as of `SchemaTypeDefinition`. I am sure we can find a better term for it. 

Similar with other classes.
1. Other
   - `TypeDefinition#getDefinition()` does not return a definition, as one may think. It returns a `JsonNode`.
   - `SwaggerSchema#getType(AbstractNode)` introduces unnecessary dependency on `AbstractNode`, just a `JsonPointer` would suffice.
   - `TypeDefinition#getPropertyType(string): TypeDefinition` - what about something like `getTypeFor()` or `getTypeForProperty()`?

## computeCompletionProposals()

A diagram which describes how `SwaggerContentAssistProcessor#computeCompletionProposals()` works:
<img width="1262" alt="screen shot 2016-09-23 at 5 28 17 pm" src="https://cloud.githubusercontent.com/assets/644582/18801828/297256be-81b3-11e6-9871-c7e101b1d57e.png">

## Get code template proposals

`SwaggerContentAssistProcessor.getContextType(ITextViewer, IRegion)` uses `currentPath` which was defined in `computeCompletionProposals()`. How do we know it's always properly initialized?

**Comment by ghillairet** [comment]
@tedepstein We are close to be able to make a PR for this, I want to have it ready for tomorrow.

What remains to be done:
- Fix the problem with locations (fix for getRegion method in item list above). This problem affects highlighting when user clicks on an hyperlink.
- Getting correct content proposals from complex JSON types (oneOf, allOf, etc..). This problem affects getting content assist from path parameters for example.

**Comment by tedepstein** [comment]
Thanks for the update, @ghillairet .  Please let me know if you need any clarifications with regard to expected behavior.

**Comment by tfesenko** [comment]
QA:
 I found only one regression so far:
Navigation from a path parameter to a parameter definition defined in another file does not work. To reproduce:
1. Extract the attached archive - [Archive.zip](https://github.com/RepreZen/SwagEdit/files/504466/Archive.zip)
2. Open `uber_path_estimates_time.yaml` line 26. Try opening a declaration (Ctrl+Click) - nothing happens. It worked in previous version.
Code assist and validation for this case work correctly.

**Comment by ghillairet** [comment]
@tfesenko Should we close this one?
