### ISSUE TITLE
Content assist in OpenAPI3 doesn't show responses in project scope.

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#317]
In this project:

[Multi-file Uber (OAS3).zip](https://github.com/RepreZen/KaiZen-OpenAPI-Editor/files/1023802/Multi-file.Uber.OAS3.zip)

Invoking code assist in `components/uber_path_user.yaml`, cycling to project scope, should suggest `"./uber_responses.yaml#/components/responses/ErrorResponse"`.  I can type in that path directly, and it passes validation without a warning.  

![image](https://cloud.githubusercontent.com/assets/692813/26376922/44ddb69a-3fdc-11e7-8b05-ecc29af83c8e.png)

But it's not suggested in code assist:

![image](https://cloud.githubusercontent.com/assets/692813/26376930/4df2a312-3fdc-11e7-9ba7-f437283bb3c4.png)

**Comment by tfesenko** [comment]
Repeatable on my machine.
The root of the problem is out regex for responses which does not respect the "default" case:
```java
RESPONSE_REGEX = ".*/responses/\\d+/\\$ref";
```
Similar with a wildcard ("3XX") response.

Changing response code to "301" or any other three-digit combination fixes code assist:
<img width="498" alt="screen shot 2017-05-23 at 5 41 11 pm" src="https://cloud.githubusercontent.com/assets/644582/26377677/46bb4b6e-3fdf-11e7-99ea-17a24056e839.png">

@tedepstein , it's an easy fix. How urgently do you need it?

**Comment by tedepstein** [comment]
@tfesenko , it's important to fix, but not especially urgent.  You can do it when it's convenient as part of the overall OpenAPI 3.0 support work.

**Comment by tfesenko** [comment]
We also need to update regex for Swagger v2, see https://github.com/RepreZen/KaiZen-OpenAPI-Editor/issues/260 
:)
