### ISSUE TITLE
OpenAPI v3: Validation of *remote* $ref property values

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#345]
OpenAPI v3: Validation of *remote* $ref property values should show error on unexpected object type, but should allow references to the expected type.

Extracted from #323 which covers validation for local $refs and $refs using relative paths.
This issue is for remote $refs, e.g. accessed with HTTP/HTTPS: `$ref: "https://raw.githubusercontent.com/RepreZen/KaiZen-OpenAPI-Editor/master/com.reprezen.swagedit.openapi3.tests/resources/spec_examples/v3.0/uber.yaml#/components/schemas/PriceEstimate"`

See https://github.com/RepreZen/KaiZen-OpenAPI-Editor/pull/342#issuecomment-305810054

**Comment by tedepstein** [comment]
It seems that the editor will always warn on an remote reference, or a certain type of external reference, even when valid.  

"Remote reference" means a reference to a document that is not in the current workspace. This problem was observed specifically on an http reference.  We don't know whether the problem applies to all remote references, or just http, or just https, maybe.

Here's a gist, with a valid OpenAPI 2.0 (Swagger) spec containing schemas:
https://gist.github.com/tedepstein/0e5f5982314f0648377df8782d7b7ccf

Here's an OpenAPI 2.0 spec with a reference to a definition in that gist (using the 'raw' URL for the gist):

```
swagger: "2.0"
info:
  description: Tax Blaster
  version: 1.0.0
  title: TaxBlaster
host: taxblaster.com
basePath: /api
schemes:
- http

paths:

  /taxFilings/{id}:

    get:
      tags:
      - TaxFilingObject
      description: Retrieves a tax filing having the specified id.
      operationId: getTaxFiling
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of the requested TaxFiling
        required: true
        type: string
      responses:
        200:
          description: Successful response, with a representation of the Tax Filing.
          schema:
            # Reference to a Schema Object described in 'definitions' section
            $ref: "https://gist.githubusercontent.com/tedepstein/0e5f5982314f0648377df8782d7b7ccf/raw/96826757aa77ddd6816ff7c3e5ca6903c0f66f2b/schemas.yaml#/definitions/PriceEstimate"
        404:
          description: The requested tax filing was not found.
```

The reference is flagged with a warning:

```
Invalid Reference - SwagEdit was unable to resolve the reference. The value must be a valid JSON Reference (for 
 external references) or JSON Pointer (for local references), and must resolve to an object of the expected type.
```

**Comment by tedepstein** [comment]
Since @ghillairet mentioned closed #390 as a duplicate, I expanded the scope of this issue to cover validation of remote references, more generally.  This includes:
* Validation _should_ show a warning or error, as appropriate, on a remote reference that cannot be resolved, or resolves to an object that does not conform to the expected type.
* Validation _should not_ show a warning on a remote reference that resolves to an object of the expected type.

**Comment by ghillairet** [comment]
See #353 and PR #358 

Changes were done in that PR to solve that issue, I still have some tests to fix.

**Comment by ghillairet** [comment]
Validation of type for external references is done in PR https://github.com/RepreZen/KaiZen-OpenAPI-Editor/pull/358
