### ISSUE TITLE
Implement Quick Outline

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#40]
It would be nice to have QuickOutline view implemented, so you press Ctrl+o (on Windows), type in a few characters, and find the definition you're looking for.

**Comment by tfesenko** [comment]
Quick outline implementation in:
- JDT - http://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/JavaOutlineInformationControl.java
- Xtext - https://github.com/eclipse/xtext/blob/master/plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/quickoutline/QuickOutlinePopup.java

One can think that you get a Quick Outline View for free if you already have a working Outline view, it's not true. Additional effort is needed, see links above.

**Comment by ghillairet** [comment]
The problems I have noted while implementing the quick outline.
- Yedit provides an outline implementation that could have been reused, especially the class YAMLOutlineElement. Unfortunately this class has a constructor that takes a snakeyaml.Node as parameter and since Yedit and SwagEdit both ship with their own snakeyaml jars, trying to instantiate that class from SwagEdit causes a class loader exception.
- Lack of documentation for setting up a quick outline correctly in a text editor. I found what it looks like a good example in mylyn wikitext plugins. The interesting classes to look at are [MarkupSourceViewerConfiguration](https://github.com/eclipse/mylyn.docs/blob/master/org.eclipse.mylyn.wikitext.ui/src/org/eclipse/mylyn/wikitext/ui/editor/MarkupSourceViewerConfiguration.java), [MarkupSourceViewer](https://github.com/eclipse/mylyn.docs/blob/master/org.eclipse.mylyn.wikitext.ui/src/org/eclipse/mylyn/wikitext/ui/editor/MarkupSourceViewer.java) and [WikiTextSourceEditor](https://github.com/eclipse/mylyn.docs/blob/master/org.eclipse.mylyn.wikitext.ui/src/org/eclipse/mylyn/wikitext
  /ui/editor/WikiTextSourceEditor.java).

Since I could not reuse outline elements from YEdit, I had to implement my owns in SwagEdit. At this time the quick outline in SwagEdit looks like this.

![screen shot 2016-07-22 at 17 17 45](https://cloud.githubusercontent.com/assets/148045/17062158/1340f61e-5032-11e6-81ec-c682309d0989.png)

**Comment by ghillairet** [comment]
Current status of the quick outline:
- Looks similar to the java one.
- Uses icons from YEdit outline, should we use our icons?

The filter does not always work correctly, sometimes it includes irrelevant elements, so it needs a little more work.

![quick](https://cloud.githubusercontent.com/assets/148045/17252360/be46a85e-55ac-11e6-8d97-bd74e3776353.gif)

**Comment by tedepstein** [comment]
@ghillairet wrote:

> Uses icons from YEdit outline, should we use our icons?

Yes, where appropriate, let's use the RepreZen / RAPID-ML icons.

**Comment by tfesenko** [comment]
While I appreciate different styling for the text and tag strings, I don't find tag information, such as "scalar" or "mapping", extremely helpful. In fact, it only confused me as it's too JSON/YAML-oriented and does not provide a lot of Swagger-specific context:
<img width="450" alt="screen shot 2016-07-29 at 12 37 02 pm" src="https://cloud.githubusercontent.com/assets/644582/17255972/6bdfa55c-5589-11e6-93b7-5fc570723377.png">
I would be happy to see something like "definition" for my TaxFiling object, or don't see details (tags) at all.

@tedepstein do you have any preferences?

**Comment by tedepstein** [comment]
Let me give it some thought & I will post back soon.

**Comment by tedepstein** [comment]
@ghillairet , @tfesenko, About the naming of elements: 

First, as soon as this has passed code review and QA, I think we should merge it.  Even without optimal names and icons, Quick Outline is an important and useful feature.

Then, to optimize the node labels:
- For single-valued primitive properties, the current `[name]: [value]` label is fine, and I think we can remove the type annotation that follows (in brown text).  I agree with Tanya, it's not helpful in this case.
- For primitive array properties, the current quick outline implementation shows a hierarchy like this: 
  ![image](https://cloud.githubusercontent.com/assets/692813/17270957/cc45120c-563c-11e6-9924-9ba7cf030ac0.png) <br/> I think this is fine, but again I think we can remove the "sequence" and "scalar" annotations.
- For single-valued object properties, I think the most useful convention is `[name] [type]`, where `[name]` is presented as the primary label (in black) and `[type]` is presented as an annotation (in brown font color).
  - Type should be taken from the schema; specifically the schema the matched the object during validation.  If a Title property is provided on the object schema, we should use that.  Otherwise, if the schema appears in the top-level definitions object, we should take the property name assigned to the schema.
  - If the schema is anonymous, i.e. declared inline without a title property, we should omit the type annotation.  We should try to avoid this by making sure all inline object schemas have titles.
  - If the object is not valid against the schema (and therefore should be marked with a validation error), we should omit the type annotation. 
- For a property whose value is an object array, the label should be the property name without a type annotation.
- For an object array element, we should also use the `[name]` label with a  `[type]` annotation.
  - The type annotation should be derived from the schema in the same manner as with a single-valued object property, described above.
  - The name label should be taken from the name property, if there is one.  For example, each parameter object in the parameters array (within a method object) has a required name property.  In this case, the name will appear twice: once as the primary label of the object, and again as the value of the name property within the object.
  - If no name property is provided, use "(unnamed object)" as the label.  We will try to avoid these situations, and possibly implement other rules for these cases.

**Comment by ghillairet** [comment]
@tedepstein I started to update the labels, but it's still in progress.

I issue I notice concerns the filtering of elements, some improvements should be done. On large specs (for example the twitter sample from http://editor.swagger.io), the filter takes too long to find elements, making the UI unusable.

**Comment by ghillairet** [comment]
The PR https://github.com/RepreZen/SwagEdit/pull/176 introduces some improvements to the quick outline (add type information and better labels). It also overrides the outline provided by YEdit to use our own.

![screen shot 2016-08-10 at 15 58 55](https://cloud.githubusercontent.com/assets/148045/17557423/6c100a20-5f17-11e6-857f-75bca4b11adf.png)

Note: I should probably make those type information lowercase

**Comment by tedepstein** [comment]
Yes, type information should be lower-case.  Thanks.

**Comment by tedepstein** [comment]
@ghillairet , you mentioned earlier that there were some performance and reliability problems with the outline view.  Performance will be important as we plan to make the Outline view support file->project->workspace cycling, similar to code assist.  

I haven't noticed any performance issue with Quick Outline, because I haven't tested it on a large file.  But I know that we do have significant problems with the regular outline view (not quick outline) provided by YEdit.

Do you expect that the new parser and outline view will improve performance?

**Comment by ghillairet** [comment]
I found that the major issue with YEdit outline comes from the tree that is always fully expanded. That causes the performance problem, but it can be easily solved by changing a preference in YEdit preferences menu. So the performance does not really come from parsing of yaml. 

The SwagEdit outline and quick outline however do not show a fully expanded tree, so it helps regarding performance. The new parser could help too, but I don't expect that it will offer a giant boost of performance. It will help avoid having to parse the file multiple times with different parsers (yaml, json) and traversing the parsers result multiple times. We do a lot of traversing of yaml/json nodes for content assist and building of outline elements. With the unified model, we would not need to do that much work because it already contains the information needed for content assist or outline, so that could help for performance but would certainly help making the code cleaner.

**Comment by ghillairet** [comment]
New PR for outlines https://github.com/RepreZen/SwagEdit/pull/178

This one includes updated labels and makes use of the unified model inside outlines only. Use of that model in other part of SwagEdit will be done later.

![screen](https://cloud.githubusercontent.com/assets/148045/17595977/a62a3ef0-5fef-11e6-954d-ef74d3ef09bc.png)

**Comment by tedepstein** [comment]
Looking much better!

@tfesenko , can you please provide Guillaume the icons that we use for the RAPID-ML outline and diagram views?

**Comment by tfesenko** [comment]
Bug introduced in PR #178: Outline view nodes are collapsed to second level on model update, see #178 (comment).

**Comment by tfesenko** [comment]
The Quick Outline is implemented, closing this issue.
The remaining can be addressed separately.
