### ISSUE TITLE
"Resolver Error" in RepreZen API Studio (eclipse plugin) in Swagger UI v3 View

### ISSUE THREAD

**Issue by vnalla** [RepreZen/KaiZen-OpenAPI-Editor#442]
The fix for #438 in KaiZen is fixed, and it also fixed in RepreZen API Studio plugin. However Swagger UI v3 View bundled in RepreZen Studio is not able to resolve $ref. 

Here is the error message for $ref URL reference:
```
Errors
Resolver error at components.schemas.Address.$ref
Could not resolve reference because of: Network request failed
```
Here is the error message for $ref with local reference:
```
Errors
Resolver error at components.schemas.Address.$ref
Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: 'components/Address.yaml' basePath: 'undefined'
```
The URL $ref works fine in Swagger-UI deployed in Tomcat server.

![image](https://user-images.githubusercontent.com/11826854/39831665-2dcd562e-5393-11e8-85df-f4c71faddf74.png)

Thanks,
Venkat

**Comment by tedepstein** [comment]
Hi Venkat, 

Thanks for reporting this. The error you see in the Swagger-UI view is actually a separate bug, and that fix will be included in a patch release of API Studio, coming soon. 

However, we're tracking API Studio support issues separately in the [RepreZen Support & Community Portal](http://support.reprezen.com) and internally in Jira. You can also send email to support@RepreZen.com, and this will automatically open a support ticket.

So I'll close this issue here for now. Please look for an update notification in API Studio within the next week or two. 

-Ted
