### ISSUE TITLE
No repository found at http://products.reprezen.com/swagedit/latest/

### ISSUE THREAD

**Issue by vwgoastephenk** [RepreZen/KaiZen-OpenAPI-Editor#484]
I've tried to install into Eclipse using the Marketplace and via Add New Software and getting an error: No repository found at http://products.reprezen.com/swagedit/latest/.

I also tried using the last release update site: http://products.reprezen.com/swagedit/0.8.0.201808281437/ with the same result.

Can someone point me to a working update site?

My Eclipse version:

Eclipse Java EE IDE for Web Developers.
Version: 2018-09 (4.9.0)
Build id: 20180917-1800

Thanks,

Stephen

**Comment by tedepstein** [comment]
@vwgoastephenk , it's working for me.  I'm able to install KaiZen Editor from the http://products.reprezen.com/swagedit/latest/ site as expected.

A few ideas to help troubleshoot:
* Can you try the same URL with `https` instead of `http` protocol? 
* Can you [check the bitness](https://support.reprezen.com/support/solutions/articles/6000118494-solution-java-requirement-error-messages) of your Eclipse IDE and Java installation? I am running with 64-bit Eclipse and Java; we generally do not test with 32-bit, and it's possible that the update site does not support it. 
* Are you able to access the directory listing at that address in a browser? You should see something like this: 
![image](https://user-images.githubusercontent.com/692813/52879540-6805a300-312d-11e9-9314-a9f9cbd56b37.png)
    * If you're able to see it properly in a regular browser, please try it from the Eclipse internal browser view. 
    * If it works from a regular browser, but not from the Eclipse browser, it could indicate a firewall issue. In that case, please try the [proxy settings](https://help.eclipse.org/2018-09/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-net-preferences.htm) Even if the page does load and render correctly from the Eclipse browser view, it may still be worth checking your proxy configuration if you don't find any other likely causes.

**Comment by vwgoastephenk** [comment]
Switching to use HTTPS - so https://products.reprezen.com/swagedit/latest/ - worked.  Thanks for your help.
