### ISSUE TITLE
Artwork for SwagEdit

### ISSUE THREAD

**Issue by tfesenko** [RepreZen/KaiZen-OpenAPI-Editor#5]
We will need icons for 
- The Swagger .yaml file and
- The new Swagger file wizard.

**Comment by tedepstein** [comment]
Please use the logo here for a Swagger YAML file:
https://github.com/swagger-api/swagger-spec/blob/master/swagger-logo.jpg

I will ask SmartBear to confirm that this is appropriate and legal use of their trademark.  

You can resize the icon, and adorn it with overlays as needed (e.g. "star" overlay for new file toolbar button)

**Comment by ghillairet** [comment]
The default swagger icon has been added for yaml file, the swagger editor and in the new swagger file wizard.

**Comment by tfesenko** [comment]
Since we already have an Outline view, we can also add custom icons to the Outline view. it's optional because the default icons are green (like the swagger icon) and look appropriate:
<img width="422" alt="screen shot 2015-10-15 at 3 12 29 pm" src="https://cloud.githubusercontent.com/assets/644582/10524769/398bc878-734f-11e5-9049-109ecf107e66.png">

**Comment by tedepstein** [comment]
@ghillairet , not sure which Swagger logo SwagEdit currently uses in File Explorer, etc.  It should use the one in the attached Zip file, which are scaled directly from a 200 x 200 logo used on the Swagger github projects. 

[Swagger Logo.zip](https://github.com/ModelSolv/SwagEdit/files/81555/Swagger.Logo.zip)

Note that the logo includes a white circle around the green circle, and a very thin gray border around the white circle. Scaling the logo down makes the thin gray border invisible.
[Eclipse guidelines](https://wiki.eclipse.org/User_Interface_Guidelines#Icon_Size_.26_Placement) suggest using a 15x15 px image for model objects (including files and projects). But the 16x16 image might work better, because of the white outline. Please feel free to try both, and use whichever one works better.

**Comment by ghillairet** [comment]
We were using this logo https://github.com/OAI/OpenAPI-Specification/blob/master/swagger-logo.jpg

I change it to use the one you provided in the zip file. I made use of 16x16 logo for small items.

**Comment by tfesenko** [comment]
Icons are updated.
